from os.path import normpath, exists
from shutil import copyfile, move, rmtree

from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider

HTTP = HTTPRemoteProvider()

from snakemake.utils import min_version

min_version("7.7")

if not exists("config/config.yaml"):
    copyfile("config/config.default.yaml", "config/config.yaml")

configfile: "config/config.yaml"

run = config.get("run", {})
RDIR = run["name"] + "/" if run.get("name") else ""
CDIR = RDIR if not run.get("shared_cutouts") else ""

LOGS = "logs/" + RDIR
BENCHMARKS = "benchmarks/" + RDIR
RESOURCES = "resources/" + RDIR if not run.get("shared_resources") else "resources/"
RESULTS = "results/" + RDIR


wildcard_constraints:
    year="[0-9]+(m|c)?|all",
    source_id="[-+a-zA-Z0-9]*",
    variant_label="[-+a-zA-Z0-9]*",
    experiment_id="[-+a-zA-Z0-9]*"

rule all:
    params:
        source_id=config["scenario"]["source_id"],
        variant_label=config["scenario"]["variant_label"],
        experiment_id=config["scenario"]["experiment_id"],
        year=config["scenario"]["year"],
    input:
        # expand("cutout_cmip6/Europe_{source_id}_{variant_label}_{experiment_id}_{year}.nc")
        "../../../com/meenergy/cutouts_cmip6/EC-Earth3/Europe_EC-Earth3_r4i1p1f1_ssp126_2034.nc"

if config["enable"].get("retrieve_cutout_cmip6", True):

    rule retrieve_cutout_cmip6:
        params:
            source_id=config["scenario"]["source_id"],
            variant_label=config["scenario"]["variant_label"],
            experiment_id=config["scenario"]["experiment_id"],
            year=config["scenario"]["year"],
        input:
        output:
           "../../../com/meenergy/cutouts_cmip6/EC-Earth3/Europe_{source_id}_{variant_label}_{experiment_id}_{year}.nc",
        log:
            LOGS + CDIR + "Europe_{source_id}_{variant_label}_{experiment_id}_{year}.log",
        resources:
            mem_mb=5000,
        benchmark:
            BENCHMARKS + "Europe_{source_id}_{variant_label}_{experiment_id}_{year}"
        script:
            "scripts/retrieve_cmip6.py"
    
